app:
  id: ""
  env: "PROD"
  name:    "ntn-products-jde-salesforce-sync-app"
  
http:
  host: "0.0.0.0"
  port: "8081"
  timeout: "15000"

sf:
  user: "mulesoftintegration@ntnusa.com"
  authURL : "https://login.salesforce.com/services/Soap/u/56.0"
  URL: "https://ntnconnect.my.salesforce.com/services/oauth2/token"  
  
db:
  host: "129.147.16.38"
  port: "1521"
  svc: "jdeorcl.netuenazr.vcnzgqox.oraclevcn.com"

pricebooks:
  host: "ntn-pricebooks-jde-sf-sync-app-prod-xbmlkc.xryhvh.usa-e2.cloudhub.io"
  port: "443"
  basePath : "/api/"
  uri : "pricebooks"