db:
  password: "![uMrGHbWyEL54QEMh+18S/A==]"
  user: "![7QqCW9QjsxUigvR2UPZDgw==]"
  
#ntn web service details
sf:
  password : "![hRt1ri9KnH5UalfO4hI4Vg==]"
  token : "![1O3V3uqG9wtByGHznFQhsc1Q4BYp3HsPQbnzOU3Ieso=]" 
  key: "![x/CzuYzqCo6gD0ZANTB1PXcZfvrstbY4Zv6lQf+nnituQawgbvIt9qJcbO5Vi+ZC5Jh0rXnHv4kOZBDB3lz2dfVQcbyEyA7VBNrmkZZ6QZ8sbYyk3OR7Ug==]"
  secret: "![4JCZ/tP9UvTssYat4vq8ASvtVOCdjQXSAA7rCbhwDtp48I03NZJE+6poXrIoW9JabgImZYfzgFuWS4I0TSjPGfEXelO21Gk0]"
 
smtp:
  user: "![hRt1ri9KnH7VngaJcayGZ0D8arLBERHy1f3i+Ca4XPI=]"
  password: "![Yk3HBzCPPp5RL3nOfWNzirX1mi98hVMs]"