%dw 2.0
output text/plain
--- 
"WITH

COLEDG07_F4105 AS (
 ---Based on changed since last run (review  COUMPJ and COTDAY)Hold variable COLITM
    Select TRIM(X1.COLITM) AS COLITM, TRIM(X1.COLEDG) AS COLEDG, TRIM(X1.COUPMJ) AS COUPMJ, TRIM(X1.COTDAY) AS COTDAY, TRIM(X1.COMCU) AS COMCU
    FROM TESTDTA.F4105 X1
    WHERE  X1.COLEDG='07' AND COMCU='1801' AND (TRIM(X1.COUPMJ) >= $(vars.previouscifJobRun.date) AND TRIM(X1.COTDAY) >= $(vars.previouscifJobRun.time))
	--AND TRIM(X1.COLITM)='6203[TB00]' 
	 
),

IBPRP1_IBSRP4_COLITM AS (
---Query PRP1 and SRP4 where LITM = (COLITM) and IBMCU=1801.Hold the variables PRP1 and SRP4
    SELECT DISTINCT 
    TRIM(TT1.IBPRP1) AS IBPRP1, 
    TRIM(TT1.IBSRP4) AS IBSRP4, 
    TRIM(TT1.IBLITM) AS IBLITM, 
    TRIM(TT1.IBMCU) AS IBMCU
    FROM TESTDTA.F4102 TT1
    INNER JOIN COLEDG07_F4105 TT2 ON TRIM(TT1.IBLITM)=TRIM(TT2.COLITM)
),

IMDRAW_IMSRTX_COLITM AS (
---Query IMDRAW and IMSRTX where LITM = (COLITM) and IBMCU=1801.Hold the variables IMDRAW and IMSRTX
    SELECT TRIM(TT3.IMDRAW) AS IMDRAW, TRIM(TT3.IMSRTX) AS IMSRTX, TRIM(TT3.IMLITM) AS IMLITM
    FROM TESTDTA.F4101 TT3
    INNER JOIN COLEDG07_F4105 TT2 ON TRIM(TT3.IMLITM)=TRIM(TT2.COLITM)
 
),

IMLITM_IMDRAW AS (
    -- Query IMLITM where IMDRAW = (variable) IMDRAW and where IMPRP1 = IBPRP1 and IMSRP4 = IBSRP4
    SELECT 
        TRIM(TT6.IMDRAW) AS IMDRAW, 
        TRIM(TT6.IMLITM) AS IMLITM, 
        TRIM(TT6.IMPRP1) AS IMPRP1, 
        TRIM(TT6.IMSRP4) AS IMSRP4
    FROM TESTDTA.F4101 TT6
    INNER JOIN IMDRAW_IMSRTX_COLITM TT7 ON TRIM(TT6.IMDRAW) = TRIM(TT7.IMDRAW)
    INNER JOIN IBPRP1_IBSRP4_COLITM TT8 ON 
        TRIM(TT6.IMPRP1) = TRIM(TT8.IBPRP1) AND 
        TRIM(TT6.IMSRP4) = TRIM(TT8.IBSRP4)
),

IMLITM_ISRTX AS (
---Query IMLITM where IMSRTX = (variable) IMSRTX
    SELECT TRIM(TT6.IMLITM) AS IMLITM, TRIM(TT6.IMSRTX) AS IMSRTX
    FROM TESTDTA.F4101 TT6
    INNER JOIN IMDRAW_IMSRTX_COLITM TT7 ON TRIM(TT6.IMSRTX)= TRIM(TT7.IMSRTX)
)

SELECT 
T3.IBPRP1 AS IBPRP1_COLITM,
T3.IBSRP4 AS IBSRP4_COLITM,
T4.IMDRAW AS IMDRAW_COLITM,
T4.IMSRTX AS IMSRTX_COLITM

FROM TESTDTA.F4102 T1
INNER JOIN TESTDTA.F4101 T2 ON
	TRIM(T1.IBLITM)=TRIM(T2.IMLITM)
	AND TRIM(T1.IBMCU)='1801'
LEFT JOIN IBPRP1_IBSRP4_COLITM T3 ON
     TRIM(T3.IBMCU)='1801'
LEFT JOIN IMDRAW_IMSRTX_COLITM T4 ON
     TRIM(T2.IMLITM)=TRIM(T4.IMLITM)
LEFT JOIN COLEDG07_F4105 T5 ON
    TRIM(T5.COMCU)=TRIM(T1.IBMCU)

--WHERE T2.IMLITM = '6203[TB00]'
WHERE (T5.COUPMJ >= $(vars.previouscifJobRun.date)) AND (T5.COTDAY >= $(vars.previouscifJobRun.time)) 
 
GROUP BY
    T3.IBPRP1, T3.IBSRP4, T4.IMDRAW, T4.IMSRTX"