%dw 2.0
output text/plain
--- 
"WITH

COLEDG07_F4105 AS (
    SELECT TRIM(X1.COLITM) AS COLITM, TRIM(X1.COITM) AS COITM,
           X1.COUPMJ, X1.COTDAY, TRIM(X1.COMCU) AS COMCU
    FROM PRODDTA.F4105 X1
    WHERE TRIM(X1.COLEDG) = '07'
      AND TRIM(X1.COMCU) = '1801'
      AND (X1.COUPMJ > $(vars.previouscifJobRun.date)
           OR (X1.COUPMJ = $(vars.previouscifJobRun.date)
               AND X1.COTDAY >= $(vars.previouscifJobRun.time)))
),

IBPRP1_IBSRP4_COLITM AS (
    SELECT DISTINCT
        TRIM(TT1.IBPRP1) AS IBPRP1, TRIM(TT1.IBSRP4) AS IBSRP4,
        TRIM(TT1.IBLITM) AS IBLITM, TRIM(TT1.IBITM) AS IBITM
    FROM PRODDTA.F4102 TT1
    INNER JOIN COLEDG07_F4105 TT2 ON TRIM(TT1.IBITM) = TRIM(TT2.COITM)
    WHERE TRIM(TT1.IBMCU) = '1801'
),

IMDRAW_IMSRTX_COLITM AS (
    SELECT TRIM(TT3.IMDRAW) AS IMDRAW, TRIM(TT3.IMSRTX) AS IMSRTX,
           TRIM(TT3.IMITM) AS IMITM, TRIM(TT3.IMLITM) AS IMLITM
    FROM PRODDTA.F4101 TT3
    INNER JOIN COLEDG07_F4105 TT2 ON TRIM(TT3.IMITM) = TRIM(TT2.COITM)
),

IMLITM_IMDRAW AS (
    SELECT TRIM(TT6.IMDRAW) AS IMDRAW, TRIM(TT6.IMLITM) AS IMLITM,
           TRIM(TT6.IMITM) AS IMITM, TRIM(TT6.IMPRP1) AS IMPRP1,
           TRIM(TT6.IMSRP4) AS IMSRP4
    FROM PRODDTA.F4101 TT6
    INNER JOIN IMDRAW_IMSRTX_COLITM TT7 ON TRIM(TT6.IMDRAW) = TRIM(TT7.IMDRAW)
),

COUNCS_IMDRAW AS (
    SELECT TT8.COUNCS / 10000 AS COUNCS,
           TRIM(TT8.COLITM) AS COLITM, TRIM(TT8.COITM) AS COITM
    FROM PRODDTA.F4105 TT8
    INNER JOIN IMLITM_IMDRAW TT9 ON TRIM(TT9.IMITM) = TRIM(TT8.COITM)
    WHERE TRIM(TT8.COLEDG) = '07'
      AND TRIM(TT8.COMCU) = '1801'
)

SELECT
    T2.IMLITM,
    T6.IMDRAW,
    T6.IMSRTX,
    MAX(T9.COUNCS) AS MAX_COUNCS_IMDRAW,
    MIN(T9.COUNCS) AS MIN_COUNCS_IMDRAW

FROM PRODDTA.F4101 T2
INNER JOIN IMDRAW_IMSRTX_COLITM T6 ON TRIM(T2.IMLITM) = TRIM(T6.IMLITM)
LEFT JOIN IBPRP1_IBSRP4_COLITM T5 ON TRIM(T2.IMLITM) = TRIM(T5.IBLITM)
LEFT JOIN IMLITM_IMDRAW T7 ON TRIM(T7.IMLITM) = TRIM(T2.IMLITM)
LEFT JOIN COUNCS_IMDRAW T9 ON TRIM(T9.COLITM) = TRIM(T2.IMLITM)

WHERE EXISTS (
    SELECT 1 FROM COLEDG07_F4105 T4
    WHERE TRIM(T4.COITM) = TRIM(T2.IMITM)
)

GROUP BY T2.IMLITM, T6.IMDRAW, T6.IMSRTX"