%dw 2.0
output text/plain
--- 
"WITH
COLEDG07_F4105 AS (
																				   
    SELECT TRIM(X1.COLITM) AS COLITM, TRIM(X1.COITM) AS COITM, X1.COUPMJ, X1.COTDAY, TRIM(X1.COMCU) AS COMCU
    FROM PRODDTA.F4105 X1
    WHERE TRIM(X1.COLEDG) = '07'AND TRIM(X1.COMCU) = '1801'
    AND (X1.COUPMJ > $(vars.previouscifJobRun.date)OR (X1.COUPMJ = $(vars.previouscifJobRun.date) AND X1.COTDAY >= $(vars.previouscifJobRun.time)))
),

IBPRP1_IBSRP4_COLITM AS (
																							
    SELECT DISTINCT
    TRIM(TT1.IBPRP1) AS IBPRP1, TRIM(TT1.IBSRP4) AS IBSRP4,
	TRIM(TT1.IBLITM) AS IBLITM, TRIM(TT1.IBITM) AS IBITM
	FROM PRODDTA.F4102 TT1
    INNER JOIN COLEDG07_F4105 TT2 ON TRIM(TT1.IBLITM) = TRIM(TT2.COLITM) WHERE TRIM(TT1.IBMCU) = '1801'
),

IMDRAW_IMSRTX_COLITM AS (
																																					  
    SELECT TRIM(TT3.IMDRAW) AS IMDRAW, TRIM(TT3.IMSRTX) AS IMSRTX, TRIM(TT3.IMLITM) AS IMLITM, TRIM(TT3.IMITM) AS IMITM
    FROM PRODDTA.F4101 TT3
    INNER JOIN COLEDG07_F4105 TT2 ON TRIM(TT3.IMITM) = TRIM(TT2.COITM)
 
),

IMLITM_ISRTX AS (
												
		   
    SELECT TRIM(TT6.IMLITM) AS IMLITM, TRIM(TT6.IMSRTX) AS IMSRTX, TRIM(TT6.IMDRAW) AS IMDRAW, TRIM(TT6.IMITM) AS IMITM
								
    FROM PRODDTA.F4101 TT6
    INNER JOIN IMDRAW_IMSRTX_COLITM TT7 ON TRIM(TT6.IMSRTX) = TRIM(TT7.IMSRTX)
),

COUNCS_IMSRTX AS (
																	 
    SELECT TT8.COUNCS / 10000 AS COUNCS, TRIM(TT8.COLITM) AS COLITM,
           TRIM(TT8.COMCU) AS COMCU, TRIM(TT8.COITM) AS COITM
    FROM PRODDTA.F4105 TT8
    INNER JOIN IMLITM_ISRTX TT10 ON TRIM(TT10.IMITM) = TRIM(TT8.COITM)
    WHERE TRIM(TT8.COLEDG) = '07' AND TRIM(TT8.COMCU) = '1801'
)

SELECT
    T2.IMLITM,
    T8.IMSRTX,
    T8.IMDRAW,
    MAX(T10.COUNCS) AS MAX_COUNCS_IMSRTX,
    MIN(T10.COUNCS) AS MIN_COUNCS_IMSRTX

FROM PRODDTA.F4101 T2
LEFT JOIN COLEDG07_F4105 T4 ON TRIM(T2.IMLITM) = TRIM(T4.COLITM)
LEFT JOIN IBPRP1_IBSRP4_COLITM T5 ON TRIM(T2.IMLITM) = TRIM(T5.IBLITM)
LEFT JOIN IMDRAW_IMSRTX_COLITM T6 ON TRIM(T2.IMLITM) = TRIM(T6.IMLITM)
LEFT JOIN IMLITM_ISRTX T8 ON TRIM(T8.IMLITM) = TRIM(T2.IMLITM)
LEFT JOIN COUNCS_IMSRTX T10 ON TRIM(T10.COLITM) = TRIM(T2.IMLITM)

WHERE (
    T4.COUPMJ > $(vars.previouscifJobRun.date)
    OR (T4.COUPMJ = $(vars.previouscifJobRun.date)
        AND T4.COTDAY >= $(vars.previouscifJobRun.time))
						  
									
)
AND TRIM(T4.COMCU) = '1801'
							  
							  
					  
						


									
								   
																															 

		
GROUP BY T2.IMLITM, T8.IMDRAW, T8.IMSRTX"