%dw 2.0
output text/plain
--- 
"WITH

IBLTLV_IBLITM AS (
    SELECT TRIM(TT1.IBLITM) AS IBLITM, TRIM(TT1.IBITM) AS IBITM,
           TT1.IBLTLV AS IBLTLV, TRIM(TT1.IBMCU) AS IBMCU
    FROM PRODDTA.F4102 TT1
    WHERE (TT1.IBUPMJ > $(vars.previousepltJobRun.date)
           OR (TT1.IBUPMJ = $(vars.previousepltJobRun.date)
               AND TT1.IBTDAY >= $(vars.previousepltJobRun.time)))
      AND TT1.IBMCU = '1801'
),

IBLTLV_IBPRP1_IBSRP4 AS (
    SELECT TRIM(TT2.IBPRP1) AS IBPRP1, TRIM(TT2.IBSRP4) AS IBSRP4,
           TRIM(TT2.IBLITM) AS IBLITM, TRIM(TT2.IBITM) AS IBITM
    FROM PRODDTA.F4102 TT2
    INNER JOIN IBLTLV_IBLITM TT3 ON TRIM(TT2.IBITM) = TRIM(TT3.IBITM)
    WHERE TRIM(TT2.IBMCU) = '1801'
),

IMDRAW_IMSRTX_IBLTLV AS (
    SELECT TRIM(TT3.IMDRAW) AS IMDRAW, TRIM(TT3.IMSRTX) AS IMSRTX,
           TRIM(TT3.IMLITM) AS IMLITM, TRIM(TT3.IMITM) AS IMITM
    FROM PRODDTA.F4101 TT3
    INNER JOIN IBLTLV_IBLITM TT4 ON TRIM(TT3.IMITM) = TRIM(TT4.IBITM)
),

IMLITM_IMDRAW_IBLTLV AS (
    SELECT TRIM(TT5.IMLITM) AS IMLITM, TRIM(TT5.IMITM) AS IMITM,
           TRIM(TT6.IMDRAW) AS IMDRAW, TRIM(TT5.IMPRP1) AS IMPRP1,
           TRIM(TT5.IMSRP4) AS IMSRP4
    FROM PRODDTA.F4101 TT5
    INNER JOIN IMDRAW_IMSRTX_IBLTLV TT6 ON TRIM(TT5.IMDRAW) = TRIM(TT6.IMDRAW)
    INNER JOIN IBLTLV_IBPRP1_IBSRP4 TT7
        ON TRIM(TT5.IMPRP1) = TRIM(TT7.IBPRP1)
        AND TRIM(TT5.IMSRP4) = TRIM(TT7.IBSRP4)
),

IMLITM_IMSRTX_IBLTLV AS (
    SELECT TRIM(TT6.IMLITM) AS IMLITM, TRIM(TT6.IMSRTX) AS IMSRTX
    FROM PRODDTA.F4101 TT6
    INNER JOIN IMDRAW_IMSRTX_IBLTLV TT7 ON TRIM(TT6.IMSRTX) = TRIM(TT7.IMSRTX)
),

MINMAX_IBLTLV_IMDRAW AS (
    SELECT TRIM(TT14.IBLITM) AS IBLITM, TRIM(TT14.IBITM) AS IBITM,
           TT14.IBLTLV AS IBLTLV
    FROM PRODDTA.F4102 TT14
    INNER JOIN IMLITM_IMDRAW_IBLTLV TT15 ON TRIM(TT14.IBITM) = TRIM(TT15.IMITM)
    WHERE TRIM(TT14.IBMCU) = '1801'
      AND EXISTS (
          SELECT 1 FROM IMLITM_IMSRTX_IBLTLV F41
          WHERE TRIM(F41.IMSRTX) = (
              SELECT TRIM(IMSRTX) FROM PRODDTA.F4101
              WHERE TRIM(IMDRAW) = TRIM(TT15.IMDRAW)
              AND ROWNUM = 1
          )
      )
)

SELECT
    T3.IBPRP1 AS IBPRP1_IBLTV,
    T3.IBSRP4 AS IBSRP4_IBLTV,
    T4.IMDRAW AS IMDRAW_IBLTV,
    T4.IMSRTX AS IMSRTX_IBLTV,
    MIN(T5.IBLTLV) AS MIN_IBLTLV_DRAW,
    MAX(T5.IBLTLV) AS MAX_IBLTLV_DRAW

FROM IBLTLV_IBLITM T1
INNER JOIN PRODDTA.F4101 T2 ON TRIM(T1.IBLITM) = TRIM(T2.IMLITM)
LEFT JOIN IBLTLV_IBPRP1_IBSRP4 T3 ON TRIM(T3.IBLITM) = TRIM(T1.IBLITM)
LEFT JOIN IMDRAW_IMSRTX_IBLTLV T4 ON TRIM(T4.IMLITM) = TRIM(T2.IMLITM)
LEFT JOIN MINMAX_IBLTLV_IMDRAW T5 ON TRIM(T5.IBLITM) = TRIM(T1.IBLITM)

GROUP BY T3.IBPRP1, T3.IBSRP4, T4.IMDRAW, T4.IMSRTX"